from __future__ import annotations

import json
from pathlib import Path

import joblib
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from .config import ARTIFACT_DIR, CLASSES, FEATURE_NAMES, FIRMWARE_MODEL_HEADER
from .features import extract_features

MODEL_PATH = ARTIFACT_DIR / "model.joblib"
METRICS_PATH = ARTIFACT_DIR / "metrics.json"


def feature_matrix(windows: np.ndarray) -> np.ndarray:
    return np.asarray([extract_features(window) for window in windows], dtype=np.float32)


def train(windows: np.ndarray, labels: np.ndarray, seed: int = 42) -> tuple[Pipeline, dict]:
    features = feature_matrix(windows)
    label_to_index = {label: index for index, label in enumerate(CLASSES)}
    encoded_labels = np.asarray([label_to_index[str(label)] for label in labels])
    x_train, x_test, y_train, y_test = train_test_split(
        features, encoded_labels, test_size=0.2, random_state=seed, stratify=encoded_labels
    )
    model = Pipeline([
        ("scale", StandardScaler()),
        ("classifier", MLPClassifier(
            hidden_layer_sizes=(24,), activation="relu", solver="adam",
            alpha=0.001, max_iter=1000, early_stopping=False,
            random_state=seed,
        )),
    ])
    model.fit(x_train, y_train)
    predictions = model.predict(x_test)
    class_indices = list(range(len(CLASSES)))
    report = classification_report(
        y_test, predictions, labels=class_indices, target_names=CLASSES,
        output_dict=True, zero_division=0,
    )
    metrics = {
        "accuracy": float(accuracy_score(y_test, predictions)),
        "macro_f1": float(f1_score(y_test, predictions, labels=class_indices, average="macro")),
        "confusion_matrix": confusion_matrix(y_test, predictions, labels=class_indices).tolist(),
        "classification_report": report,
        "train_samples": int(len(x_train)),
        "test_samples": int(len(x_test)),
        "feature_count": len(FEATURE_NAMES),
    }
    return model, metrics


def save_bundle(model: Pipeline, metrics: dict) -> None:
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, MODEL_PATH)
    METRICS_PATH.write_text(json.dumps(metrics, indent=2) + "\n")
    export_cpp_header(model, FIRMWARE_MODEL_HEADER)


def load_bundle(path: Path = MODEL_PATH) -> Pipeline:
    if not path.exists():
        raise FileNotFoundError(f"model not found at {path}; run `edge-pdm train` first")
    return joblib.load(path)


def predict_window(model: Pipeline, window: np.ndarray) -> tuple[str, float, dict, np.ndarray]:
    features = extract_features(window)
    probabilities = model.predict_proba(features.reshape(1, -1))[0]
    classes = model.named_steps["classifier"].classes_.astype(int)
    best = int(np.argmax(probabilities))
    probability_map = {CLASSES[index]: float(value) for index, value in zip(classes, probabilities)}
    return CLASSES[classes[best]], float(probabilities[best]), probability_map, features


def _cpp_array(name: str, values: np.ndarray) -> str:
    flat = np.asarray(values).flatten()
    body = ", ".join(f"{float(value):.9g}f" for value in flat)
    return f"constexpr float {name}[{len(flat)}] = {{{body}}};"


def export_cpp_header(model: Pipeline, destination: Path) -> None:
    scaler: StandardScaler = model.named_steps["scale"]
    classifier: MLPClassifier = model.named_steps["classifier"]
    if len(classifier.coefs_) != 2:
        raise ValueError("firmware exporter supports exactly one hidden layer")

    input_weights = classifier.coefs_[0].T
    output_weights = classifier.coefs_[1].T
    classes = [CLASSES[int(item)] for item in classifier.classes_]
    content = f"""// Generated by edge-pdm train. Do not edit manually.
#pragma once

#include <Arduino.h>

namespace model_data {{
constexpr size_t kFeatureCount = {input_weights.shape[1]};
constexpr size_t kHiddenCount = {input_weights.shape[0]};
constexpr size_t kClassCount = {output_weights.shape[0]};
constexpr const char* kClassNames[kClassCount] = {{{', '.join(json.dumps(x) for x in classes)}}};
{_cpp_array('kFeatureMean', scaler.mean_)}
{_cpp_array('kFeatureScale', scaler.scale_)}
{_cpp_array('kInputWeights', input_weights)}
{_cpp_array('kHiddenBias', classifier.intercepts_[0])}
{_cpp_array('kOutputWeights', output_weights)}
{_cpp_array('kOutputBias', classifier.intercepts_[1])}
}}  // namespace model_data
"""
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content)
